spring.application.name=simulator
traffic.update-interval-ms=3000
spring.profiles.default=local

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/traffic_simulator}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres@11}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
