spring.datasource.url=jdbc:postgresql://localhost:5432/traffic_simulator
spring.datasource.username=postgres
spring.datasource.password=postgre@11
spring.datasource.driver-class-name=org.postgresql.Driver
